[versions]
# Android y Kotlin
agp = "8.13.2"
kotlin = "2.1.0"
# Ksp
ksp = "2.1.0-1.0.29"
coreKtx = "1.18.0"
# Testing
junit = "4.13.2"
junitTest = "1.3.0"
rulesTest = "1.7.0" # Incluye androidx.test:runner
espresso = "3.7.0"
mockk = "1.14.11"
coroutines-test = "1.11.0"
turbine = "1.2.1"
# Lifecycle & XML
lifecycleRuntimeKtx = "2.11.0"
appcompat = "1.7.1"
material = "1.14.0"
activity = "1.13.0"
fragmentKtx = "1.8.9"
# Navigation
navVersion = "2.9.8"
# Network
retrofit = "3.0.0"
gson = "2.14.0"
loggingInterceptor = "5.4.0"
# Dependency Injection (Hilt)
hilt = "2.54"
# Google Play Billing
billing = "9.1.0"
# Firebase y Servicios de Google
firebaseVersion = "33.0.0"
gms = "4.5.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navVersion" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navVersion" }

android-billingclient-billing = { module = "com.android.billingclient:billing", version.ref = "billing" }

squareup-retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit2-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
google-code-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseVersion" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }

squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitTest" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "rulesTest" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "gms" }